package com.skwen.voicerecord.voicelib.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.skwen.voicerecord.voicelib.entity.Voice;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VOICE".
*/
public class VoiceDao extends AbstractDao<Voice, Long> {

    public static final String TABLENAME = "VOICE";

    /**
     * Properties of entity Voice.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VoiceName = new Property(1, String.class, "voiceName", false, "VOICE_NAME");
        public final static Property VoiceTime = new Property(2, String.class, "voiceTime", false, "VOICE_TIME");
        public final static Property VoicePath = new Property(3, String.class, "voicePath", false, "VOICE_PATH");
    }


    public VoiceDao(DaoConfig config) {
        super(config);
    }
    
    public VoiceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VOICE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"VOICE_NAME\" TEXT," + // 1: voiceName
                "\"VOICE_TIME\" TEXT," + // 2: voiceTime
                "\"VOICE_PATH\" TEXT);"); // 3: voicePath
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VOICE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Voice entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String voiceName = entity.getVoiceName();
        if (voiceName != null) {
            stmt.bindString(2, voiceName);
        }
 
        String voiceTime = entity.getVoiceTime();
        if (voiceTime != null) {
            stmt.bindString(3, voiceTime);
        }
 
        String voicePath = entity.getVoicePath();
        if (voicePath != null) {
            stmt.bindString(4, voicePath);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Voice entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String voiceName = entity.getVoiceName();
        if (voiceName != null) {
            stmt.bindString(2, voiceName);
        }
 
        String voiceTime = entity.getVoiceTime();
        if (voiceTime != null) {
            stmt.bindString(3, voiceTime);
        }
 
        String voicePath = entity.getVoicePath();
        if (voicePath != null) {
            stmt.bindString(4, voicePath);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Voice readEntity(Cursor cursor, int offset) {
        Voice entity = new Voice( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // voiceName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // voiceTime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // voicePath
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Voice entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVoiceName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVoiceTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setVoicePath(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Voice entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Voice entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Voice entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
